# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
{{- if .Values.watchSecrets }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robusta-secret-watcher
  labels:
    app.kubernetes.io/name: robusta-forwarder
    app.kubernetes.io/part-of: robusta
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robusta-secret-watcher
  labels:
    app.kubernetes.io/name: robusta-forwarder
    app.kubernetes.io/part-of: robusta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: robusta-secret-watcher
subjects:
  - kind: ServiceAccount
    name: robusta-forwarder-service-account
    namespace: {{ .Release.Namespace }}
  # Robusta constructs the typed Secret change event by reading the object.
  - kind: ServiceAccount
    name: robusta-runner-service-account
    namespace: {{ .Release.Namespace }}
{{- end }}
