# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/refs/heads/main/tasks.schema.json
tasks:
  - name: all
    actions:
      - cmd: python3 -m unittest tests/test_relay_profiles.py
      - task: health-check
      - cmd: bash tests/robusta.test.sh


  # Ensure application deploys successfully and becomes available
  - name: health-check
    actions:
      - description: Robusta Health Check
        wait:
          cluster:
            kind: Deployment
            name: robusta-runner
            namespace: robusta
            condition: Available
      - description: Robusta Forwarder Health Check
        wait:
          cluster:
            kind: Deployment
            name: robusta-forwarder
            namespace: robusta
            condition: Available
      - description: Alert relay Health Check
        wait:
          cluster:
            kind: Deployment
            name: robusta-alert-relay
            namespace: robusta
            condition: Available
