# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

import importlib.util
import sys
import types
import unittest
from pathlib import Path
from unittest.mock import patch


def action(function):
    return function


class ActionParams:
    def __init__(self, **values):
        for key, value in values.items():
            setattr(self, key, value)

    def post_initialization(self):
        pass


modules = {
    "kubernetes": types.SimpleNamespace(client=types.SimpleNamespace()),
    "robusta": types.ModuleType("robusta"),
    "robusta.core": types.ModuleType("robusta.core"),
    "robusta.core.model": types.ModuleType("robusta.core.model"),
    "robusta.core.model.base_params": types.SimpleNamespace(ActionParams=ActionParams),
    "robusta.core.playbooks": types.ModuleType("robusta.core.playbooks"),
    "robusta.core.playbooks.actions_registry": types.SimpleNamespace(action=action),
    "robusta.integrations": types.ModuleType("robusta.integrations"),
    "robusta.integrations.kubernetes": types.ModuleType("robusta.integrations.kubernetes"),
    "robusta.integrations.kubernetes.autogenerated": types.ModuleType("robusta.integrations.kubernetes.autogenerated"),
    "robusta.integrations.kubernetes.autogenerated.triggers": types.SimpleNamespace(PodChangeEvent=object),
}
for name, module in modules.items():
    sys.modules.setdefault(name, module)

ROOT = Path(__file__).parents[1]
spec = importlib.util.spec_from_file_location("profile_ownership", ROOT / "chart/files/profile_ownership.py")
ownership = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ownership)


def metadata(name, kind=None, owner=None, labels=None):
    owners = []
    if owner:
        owners = [types.SimpleNamespace(kind=owner[0], name=owner[1], controller=True)]
    return types.SimpleNamespace(
        name=name, namespace="application", labels=labels or {}, ownerReferences=owners,
    )


def params(resources, labels=None):
    return ownership.ProfileOwnershipParams(resources=resources, labels=labels or {})


class ProfileOwnershipTest(unittest.TestCase):
    def test_standalone_pod_matches_exact_name_and_labels(self):
        pod = types.SimpleNamespace(metadata=metadata("api", labels={"app": "api"}))
        self.assertTrue(ownership.pod_belongs_to_profile(pod, params({"Pod": ["api"]}, {"app": "api"})))
        self.assertFalse(ownership.pod_belongs_to_profile(pod, params({"Pod": ["other"]}, {"app": "api"})))

    def test_direct_workload_owners_match_and_unrelated_owners_do_not(self):
        for kind in ("StatefulSet", "DaemonSet", "Job"):
            with self.subTest(kind=kind):
                pod = types.SimpleNamespace(metadata=metadata("api-pod", owner=(kind, "api")))
                with patch.object(ownership, "_read_metadata", return_value=metadata("api", labels={"app": "api"})):
                    self.assertTrue(ownership.pod_belongs_to_profile(pod, params({kind: ["api"]}, {"app": "api"})))
                    self.assertFalse(ownership.pod_belongs_to_profile(pod, params({kind: ["other"]}, {"app": "api"})))

    def test_deployment_resolves_through_replicaset(self):
        pod = types.SimpleNamespace(metadata=metadata("web-abc-123", owner=("ReplicaSet", "web-abc")))
        replica_set = metadata("web-abc", owner=("Deployment", "web"), labels={"app": "web"})
        deployment = metadata("web", labels={"app": "web"})

        def read(kind, namespace, name):
            return replica_set if kind == "ReplicaSet" else deployment

        with patch.object(ownership, "_read_metadata", side_effect=read):
            self.assertTrue(ownership.pod_belongs_to_profile(pod, params({"ReplicaSet": ["web-abc"]}, {"app": "web"})))
            self.assertTrue(ownership.pod_belongs_to_profile(pod, params({"Deployment": ["web"]}, {"app": "web"})))
            self.assertFalse(ownership.pod_belongs_to_profile(pod, params({"Deployment": ["other"]}, {"app": "web"})))

    def test_action_fails_closed_without_stopping_other_profiles(self):
        event = types.SimpleNamespace(get_pod=lambda: types.SimpleNamespace(metadata=metadata("unowned")), named_sinks=["profile-health-relay"])
        ownership.profile_ownership_filter(event, params({"Deployment": ["web"]}))
        self.assertEqual(event.named_sinks, [])
        self.assertFalse(hasattr(event, "stop_processing"))


if __name__ == "__main__":
    unittest.main()
