# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

"""Robusta action that safely maps Pod health events to Profile workloads."""

import logging
from typing import Dict, List, Optional, Tuple

from kubernetes import client
from robusta.core.model.base_params import ActionParams
from robusta.core.playbooks.actions_registry import action
from robusta.integrations.kubernetes.autogenerated.triggers import PodChangeEvent


class ProfileOwnershipParams(ActionParams):
    resources: Dict[str, List[str]]
    labels: Dict[str, str]


def _controller_owner(metadata) -> Optional[Tuple[str, str]]:
    owners = getattr(metadata, "ownerReferences", None) or getattr(metadata, "owner_references", None) or []
    owner = next((item for item in owners if getattr(item, "controller", False)), owners[0] if owners else None)
    if not owner:
        return None
    return owner.kind, owner.name


def _labels_match(actual: Optional[Dict[str, str]], expected: Dict[str, str]) -> bool:
    actual = actual or {}
    return all(actual.get(key) == value for key, value in expected.items())


def _name_matches(kind: str, name: str, resources: Dict[str, List[str]]) -> bool:
    names = resources.get(kind)
    return names is not None and (not names or name in names)


def _read_metadata(kind: str, namespace: str, name: str):
    if kind == "Deployment":
        return client.AppsV1Api().read_namespaced_deployment(name, namespace).metadata
    if kind == "StatefulSet":
        return client.AppsV1Api().read_namespaced_stateful_set(name, namespace).metadata
    if kind == "DaemonSet":
        return client.AppsV1Api().read_namespaced_daemon_set(name, namespace).metadata
    if kind == "ReplicaSet":
        return client.AppsV1Api().read_namespaced_replica_set(name, namespace).metadata
    if kind == "Job":
        return client.BatchV1Api().read_namespaced_job(name, namespace).metadata
    raise ValueError(f"unsupported Profile workload owner: {kind}")


def _candidate_matches(kind: str, name: str, namespace: str, resources, labels) -> bool:
    if not _name_matches(kind, name, resources):
        return False
    if not labels:
        return True
    return _labels_match(_read_metadata(kind, namespace, name).labels, labels)


def pod_belongs_to_profile(pod, params: ProfileOwnershipParams) -> bool:
    """Return true only when the Pod or its verified controller belongs to the Profile."""
    namespace = pod.metadata.namespace
    pod_name = pod.metadata.name
    resources = params.resources

    if _name_matches("Pod", pod_name, resources) and _labels_match(pod.metadata.labels, params.labels):
        return True

    owner = _controller_owner(pod.metadata)
    if not owner:
        return False
    owner_kind, owner_name = owner

    if owner_kind in {"StatefulSet", "DaemonSet", "Job"}:
        return _candidate_matches(owner_kind, owner_name, namespace, resources, params.labels)

    if owner_kind != "ReplicaSet":
        return False

    replica_set = _read_metadata("ReplicaSet", namespace, owner_name)
    if _name_matches("ReplicaSet", owner_name, resources) and _labels_match(replica_set.labels, params.labels):
        return True

    replica_set_owner = _controller_owner(replica_set)
    if not replica_set_owner or replica_set_owner[0] != "Deployment":
        return False
    return _candidate_matches("Deployment", replica_set_owner[1], namespace, resources, params.labels)


@action
def profile_ownership_filter(event: PodChangeEvent, params: ProfileOwnershipParams):
    """Suppress this playbook's sinks unless the Pod belongs to a selected Profile workload."""
    try:
        pod = event.get_pod()
        matched = pod_belongs_to_profile(pod, params)
        logging.debug("Profile ownership check pod=%s resources=%s matched=%s", pod.metadata.name, params.resources, matched)
        if not matched:
            event.named_sinks = []
    except Exception:
        # Ownership uncertainty must fail closed; unrelated applications must never
        # be routed to a Profile merely because they share its namespace.
        logging.exception("Unable to verify Pod ownership for Profile health event")
        event.named_sinks = []
