# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/uds-cli/refs/heads/main/tasks.schema.json
tasks:
  - name: all
    actions:
      - task: health-check


  # Ensure application deploys successfully and becomes available
  - name: health-check
    actions:
      - description: Robusta Health Check
        wait:
          cluster:
            kind: Deployment
            name: robusta
            namespace: robusta
            condition: Available

